### ISSUE TITLE
Can't access kubeless-ui non-localhost

### ISSUE THREAD

**Issue by meysam001** [kubeless/kubeless-ui#56]
`kubeless-ui` will run on localhost:3000. I'd like to access it through server IP like 217.20.113.125:3000 .
Is there any way?
thanks

**Comment by andresmgot** [comment]
Hi @meysam001,

If you have deployed the UI using the `k8s.yaml` manifest present in this repository the `Service` will be deployed using the type `NodePort` (which means that it will only be accessible within the cluster). If you want to use a public IP to access the service you can change that `type` to use `LoadBalancer` or create an Ingress rule if you cluster has an Ingress controller. Be careful because if you do so the service will be publicly available and anyone could deploy functions in your cluster.
